"""
SCC fusion parameter tuning script.

Tests different combinations of RRF k, store weight, and floor
by modifying the YAML config files and restarting SCC services.

Usage::
    python -m seren_probe.tune_scc
"""
from __future__ import annotations

import sys
import json
import itertools
import time
import os
import signal
import subprocess
sys.path.insert(0, "/home/caesar")

import httpx
import yaml
from .dataset import seed_synthetic_dataset
from .metrics import compute_metrics_batch, grade_against_content

SCC_NV_URL = "http://localhost:7423"
SCC_V_URL  = "http://localhost:7424"

SCC_NV_YAML = "/home/caesar/seren-corpus-callosumragEvalCorpusCallosumLociBase/seren-corpus-callosum.yaml"
SCC_V_YAML  = "/home/caesar/seren-corpus-callosumragEvalCorpusCallosumLociVector/seren-corpus-callosum.yaml"

SCC_NV_VENV = "/home/caesar/seren-venvs/callosumragEvalCorpusCallosumLociBase/bin/python"
SCC_V_VENV  = "/home/caesar/seren-venvs/callosumragEvalCorpusCallosumLociVector/bin/python"


def post(url, path, body):
    r = httpx.post(f"{url}{path}", json=body, timeout=30.0)
    r.raise_for_status()
    return r.json()


def kill_by_port(port: int):
    """Kill process listening on given port."""
    try:
        result = subprocess.run(
            ["lsof", "-ti", f":{port}"],
            capture_output=True, timeout=5,
        )
        pids = result.stdout.decode().strip().split()
        for pid in pids:
            try:
                os.kill(int(pid), signal.SIGTERM)
            except Exception:
                pass
        time.sleep(1)
    except Exception:
        pass


def start_one_scc(url: str, yaml_path: str, venv: str, port: int, label: str):
    """Start one SCC service and wait for it to be ready."""
    cmd = [
        venv, "-m", "seren_corpus_callosum",
        "--config", yaml_path,
    ]
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Wait for readiness
    for _ in range(30):
        try:
            r = httpx.get(url, timeout=3.0)
            if r.status_code == 200:
                return
        except Exception:
            pass
        time.sleep(1)
    raise RuntimeError(f"SCC ({label}) failed to start at {url}")


def make_yaml(server_port: int, k: int, weight: float, floor: float, loci_url: str) -> str:
    """Build YAML config string with given params."""
    return f"""# SerenCorpusCallosum config - generated by tune_scc.py
server:
  host: 127.0.0.1
  port: {server_port}
  bearer_token: ""

federation:
  k: {k}
  n_results: 10
  stores:
    - name: memory
      type: seren_memory
      url: http://127.0.0.1:7420
      weight: 1.0
      floor: 0.0
    - name: loci
      type: seren_loci
      url: {loci_url}
      weight: {weight}
      floor: {floor}
"""


def evaluate_scc(url: str, queries: list, k: int = 10) -> dict:
    """Run SCC queries and return aggregate metrics (includes docket metrics).

    Uses the shared grade_against_content from seren_probe.metrics so the
    fuzzy normalizer and content-relevance logic are single-sourced.
    """
    results: list[tuple[list[tuple[str, float]], set[str]]] = []
    docket_coverages: list[float] = []
    docket_densities: list[float] = []
    for q in queries:
        payload = {"query": q.query, "n_results": k}
        resp = post(url, "/search", payload)
        hits = resp.get("hits", [])

        retrieved, relevant, cov, den = grade_against_content(
            hits, q.expected_content, q.expected_ids, k=k)
        results.append((retrieved, relevant))
        docket_coverages.append(cov)
        docket_densities.append(den)

    m = compute_metrics_batch(results, k=k)
    agg = m.aggregate()
    agg["docket_coverage"] = sum(docket_coverages) / len(docket_coverages) if docket_coverages else 0.0
    agg["docket_density"] = sum(docket_densities) / len(docket_densities) if docket_densities else 0.0
    return agg


def tune_one(
    url: str, label: str, queries: list,
    loci_url: str, yaml_path: str, venv: str, server_port: int,
):
    """Grid-search over RRF k, store weight, and floor via YAML restart for one SCC."""
    rrf_ks = [30, 60, 100]
    weights = [0.3, 0.5, 0.7, 1.0]
    floors  = [0.0, 0.1, 0.3]

    best: dict = {"hit_rate": 0, "mrr": 0, "params": {}}
    results: list[dict] = []

    for rrf_k, w, fl in itertools.product(rrf_ks, weights, floors):
        yaml_content = make_yaml(server_port, rrf_k, w, fl, loci_url)

        print(f"    k={rrf_k} w={w} fl={fl}  ", end="")
        try:
            # Write YAML
            with open(yaml_path, "w") as f:
                f.write(yaml_content)

            # Kill and restart this SCC service only
            kill_by_port(server_port)
            time.sleep(1)
            start_one_scc(url, yaml_path, venv, server_port, label)

            # Evaluate
            agg = evaluate_scc(url, queries, k=10)
            agg["params"] = {"rrf_k": rrf_k, "weight": w, "floor": fl}
            results.append(agg)

            hr = agg.get("hit_rate", 0)
            mr = agg.get("mrr", 0)
            pr = agg.get("precision", 0)
            rc = agg.get("recall", 0)
            nd = agg.get("ndcg", 0)
            iou = agg.get("iou", 0)
            pw = agg.get("prec_omega", 0)
            dc = agg.get("docket_coverage", 0)
            dd = agg.get("docket_density", 0)
            print(f"hit={hr:.3f} mrr={mr:.3f} prec={pr:.3f} recall={rc:.3f} ndcg={nd:.3f} "
                  f"iou={iou:.3f} p-omega={pw:.3f} docket_cov={dc:.3f} docket_den={dd:.3f}", end="")
            if hr > best["hit_rate"] or (hr == best["hit_rate"] and mr > best["mrr"]):
                best = agg
                print("  <<< BEST", end="")
            print()

        except Exception as e:
            print(f"[FAIL] {e}")
            continue

    print(f"\n  Best params for {label}:")
    base = f"    hit_rate={best.get('hit_rate',0):.3f}  mrr={best.get('mrr',0):.3f}  "
    base += f"prec={best.get('precision',0):.3f}  recall={best.get('recall',0):.3f}  "
    base += f"ndcg={best.get('ndcg',0):.3f}  iou={best.get('iou',0):.3f}  prec_omega={best.get('prec_omega',0):.3f}"
    cov = best.get('docket_coverage')
    den = best.get('docket_density')
    if cov is not None and den is not None:
        base += f"  docket_cov={cov:.3f}  docket_den={den:.3f}"
    print(base)
    print(f"    params={best.get('params', {})}")

    return best, results


def main():
    print("=" * 72)
    print("SCC Fusion Parameter Tuning")
    print("=" * 72)

    ds = seed_synthetic_dataset()
    corpus_queries = ds.filter_by_source("corpus")
    print(f"Corpus queries: {len(corpus_queries)}")

    # ── Baseline (current config) ────────────────────────────────────────
    print("\n── Baseline ──")
    for url, label in [(SCC_NV_URL, "no-vector"), (SCC_V_URL, "vector")]:
        agg = evaluate_scc(url, corpus_queries, k=10)
        base = f"  SCC ({label}):  hit={agg['hit_rate']:.3f}  mrr={agg['mrr']:.3f}  "
        base += f"prec={agg['precision']:.3f}  recall={agg['recall']:.3f}  "
        base += f"ndcg={agg['ndcg']:.3f}  iou={agg['iou']:.3f}  prec_omega={agg['prec_omega']:.3f}"
        cov = agg.get('docket_coverage')
        den = agg.get('docket_density')
        if cov is not None and den is not None:
            base += f"  docket_cov={cov:.3f}  docket_den={den:.3f}"
        print(base)

    # ── Grid search ──────────────────────────────────────────────────────
    print("\n── Grid Search ──")
    tune_one(SCC_NV_URL, "no-vector", corpus_queries,
             "http://127.0.0.1:7422", SCC_NV_YAML, SCC_NV_VENV, 7423)
    print()
    tune_one(SCC_V_URL, "vector", corpus_queries,
             "http://127.0.0.1:7421", SCC_V_YAML, SCC_V_VENV, 7424)

    # ── Restore defaults ──────────────────────────────────────────────────
    print("\n── Restoring default configs ──")
    default_nv = make_yaml(7423, 60, 1.0, 0.0, "http://127.0.0.1:7422")
    default_v  = make_yaml(7424, 60, 1.0, 0.0, "http://127.0.0.1:7421")
    for path, content in [(SCC_NV_YAML, default_nv), (SCC_V_YAML, default_v)]:
        with open(path, "w") as f:
            f.write(content)

    kill_by_port(7423)
    kill_by_port(7424)
    time.sleep(1)
    start_one_scc(SCC_NV_URL, SCC_NV_YAML, SCC_NV_VENV, 7423, "no-vector")
    start_one_scc(SCC_V_URL, SCC_V_YAML, SCC_V_VENV, 7424, "vector")
    print("  Defaults restored, SCC services restarted.")

    print("\n" + "=" * 72)
    print("Tuning complete.")
    print("=" * 72)


if __name__ == "__main__":
    main()
